name: CI

on:
  push:
    branches:
      - main
  pull_request:

  syn_provider_check:
    name: Sync Provider check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: ./sync-providers.sh --validate
